import global_var

def card():
    print('\nUPPER SECTION:')
    print('(1)Ones:             ', global_var.ones)
    print('(2)Twos:             ', global_var.twos)
    print('(3)Threes:           ', global_var.threes)
    print('(4)Fours:            ', global_var.fours)
    print('(5)Fives:            ', global_var.fives)
    print('(6)Sixes:            ', global_var.sixes)
    print('Sub Total:           ', global_var.subtotal)
    print('Bonus 35 if over 63: ', global_var.upper_bonus)
    print('Total Upper Section: ', global_var.total_upper, '\n')
    print('---------------------\n')
    print('LOWER SECTION')
    print('(1)3 of a kind:      ', global_var.threek)
    print('(2)4 of a kind:      ', global_var.fourk)
    print('(3)Full House:       ', global_var.house)
    print('(4)Small Straight:   ', global_var.sm_str)
    print('(5)Large Straight:   ', global_var.lg_str)
    print('(6)YAHTZEE:          ', global_var.yahtzee)
    print('(7)Chance:           ', global_var.chance)
    print('Yahtzee Bonus (100): ', global_var.yaht_bon)
    print('Total Lower Section: ', global_var.total_lower)
    print('Total Upper Section: ', global_var.total_upper)
    print('GRAND TOTAL:         ', global_var.grand_total, '\n')